baseurl = "https://www.karansampath.com"
copyright = "© Karan Sampath"
title = "Karan Sampath"
enablerobotstxt = true
theme="archie"
languagecode = "en-us"
timezone = "America/Los_Angeles"
titlecasestyle = "Go"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode="auto" # color-mode → light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "Personal website"
description = "Personal website"
mathjax = true # enable MathJax support
katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/karansampath"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/karan_sampath"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/karansampath/"

[[params.social]]
name = "Email"
icon = "envelope"
url = "mailto:me@karansampath.com"

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[languages.en.menu.main]]
identifier = "About Me"
name = "About Me"
url = "/about/"
weight = 2

[[languages.en.menu.main]]
identifier = "favorites"
name = "Favorites"
url = "/favorites/"
weight = 3

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 4
