baseurl = "https://www.karansampath.com"
copyright = "© Karan Sampath"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
timezone = "America/New_York"
titlecasestyle = "Go"

[languages.en]
title = "Paige"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "experiences"
name = "Experiences"
url = "/experiences/"
weight = 20

[[languages.en.menu.main]]
identifier = "interests"
name = "Interests"
url = "/interests/"
weight = 30

[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 40

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 50

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "json", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[params.authors.karan-sampath]
default = true
email = "karan.sampath02@gmail.com"
name = "Karan Sampath"
url = "https://www.karansampath.com"

[params.paige.git]
commit_url = "https://github.com/karansampath/karansampath.github.io/commit/%s"

[[params.paige.feed.atom.authors]]
email = "karan.sampath02@gmail.com"
name = "Karan Sampath"
url = "https://www.karansampath.com"

[params.paige.feed.rss]
managing_editor = "karan.sampath02@gmail.com (Karan Sampath)"
web_master = "karan.sampath02@gmail.com (Karan Sampath)"

[params.paige.file_link]
content = "Edit this page"
disable = true
url = "https://github.com/karansampath/karansampath.github.io/edit/master/content/%s"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"