baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Karan Sampath'

[[module.imports]]
path = "github.com/willfaught/paige"

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'static'
target = 'assets'
